### ISSUE TITLE
Exception in Scheduler

### ISSUE THREAD

**Issue by dignajar** [bitnami/bitnami-docker-airflow-scheduler#1]
**Description**
I got the following error in the scheduler.

I'm using PostgreSQL from AWS, and Redis from AWS.

**Steps to reproduce the issue:**

1. Create the docker container for webserver.
2. Create the docker container for the scheduler
3. In the webserver (http://localhost:8080) execute the first DAG `example_bash_operator`

**Describe the results you received:**
```
[2019-06-14 12:07:59,661] {celery_executor.py:228} ERROR - Error sending Celery task:Timeout, PID: 858
Celery Task ID: ('example_bash_operator', 'runme_0', datetime.datetime(2019, 6, 13, 0, 0, tzinfo=<TimezoneInfo [UTC, GMT, +00:00:00, STD]>), 1)
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/utils/functional.py", line 42, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 921, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/executors/celery_executor.py", line 118, in send_task_to_executor
    result = task.apply_async(args=[command], queue=queue)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/app/task.py", line 535, in apply_async
    **options
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/app/base.py", line 728, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/celery/app/amqp.py", line 552, in send_task_message
    **properties
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/connection.py", line 510, in _ensured
    return fun(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/messaging.py", line 187, in _publish
    channel = self.channel
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/messaging.py", line 209, in _get_channel
    channel = self._channel = channel()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/utils/functional.py", line 44, in __call__
    value = self.__value__ = self.__contract__()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/messaging.py", line 224, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/connection.py", line 852, in default_channel
    self.ensure_connection(**conn_opts)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/connection.py", line 422, in ensure_connection
    callback, timeout=timeout)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/utils/functional.py", line 341, in retry_over_time
    return fun(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/connection.py", line 275, in connect
    return self.connection
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/connection.py", line 823, in connection
    self._connection = self._establish_connection()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/connection.py", line 778, in _establish_connection
    conn = self.transport.establish_connection()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 941, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 923, in create_channel
    channel = self.Channel(connection)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/kombu/transport/redis.py", line 513, in __init__
    self.client.ping()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/client.py", line 1037, in ping
    return self.execute_command('PING')
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 502, in connect
    self.on_connect()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 570, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 224, in readline
    self._read_from_socket()
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/connection.py", line 182, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/redis/_compat.py", line 58, in recv
    return sock.recv(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/timeout.py", line 43, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 858
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

```
docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by ashokbalaraman** [comment]
I have the same exact problem.  Can you please detail how you resolved the issue?

**Comment by rraj123** [comment]
@ashokbalaraman - I had similar issues. The same  docker set up worked on my local set up. However, the same image and compose did not work. This is similar to this bug https://issues.apache.org/jira/browse/AIRFLOW-6527. Hence, I had to set these parameters operation_timeout and send_task_timeout attributes values to higher values. By default, it is set to 2.

**Comment by kjayan** [comment]
@dignajar How did you solve it?
@ashokbalaraman  where did you set the values for these two params?

**Comment by dignajar** [comment]
Hi, sorry I just read the notification.. we changed the approach and move to Kubernetes Executor, also I made my own Docker Image of Airflow.

**Comment by MuriloSchaefer** [comment]
I had the same issue, I'm using Elasticache from AWS to serve redis.

When redis auth token set and encryption in transit it fails with that error. I also tried to increase the timeout value as described here: https://issues.apache.org/jira/browse/AIRFLOW-6527 but it didn't work.

Removing auth token worked
